### ISSUE TITLE
Allow to move emails between folders without delete permission

### ISSUE THREAD

**Issue by aftorres** [Zimbra-Community/shared-mailbox-toolkit#17]
Hi,

Is it possible for a user to move emails between folders without having delete permission ?

Thanks

**Comment by barrydegraaff** [comment]
Hello,

To move folders you would need at least rwixd (with delete flag), and that would allow one to move the folder inside the shared account. I do not think there is an easy work-around for that. It's Zimbra by design. I do understand the usecase.

You cannot move a folder from one mailbox to another (aka move it from user-a to user-b). So even with the d-flag folders always remain in the same mailbox.
